### ISSUE TITLE
Too few params

### ISSUE THREAD

**Issue by aaryapatel007** [titu1994/keras-octconv#1]
Your OctResnet-50 model has 887K parameters while in the paper they have 25.6M?
Same for other models too.

**Comment by titu1994** [comment]
I'm using an initial convolution filters there of just 16 filters, not 64, and expansion is capped to 1, not 4 as default. 

I'll look into it if changing those gets 25M params

**Comment by titu1994** [comment]
Fixed via 463d3e35e4e65fe57b3533a268b9890aa5644563

**Comment by aaryapatel007** [comment]
Is it necessary to keep input_shape (256,256)? Can't anything less than it work?

**Comment by titu1994** [comment]
You can use as low as 32,32,3 but you need to set initial_pooling=False then.

**Comment by aaryapatel007** [comment]
Thank you! I've set `initial_strides = False`
