### ISSUE TITLE
Model only compile-able when alpha = 0.5

### ISSUE THREAD

**Issue by ziyigogogo** [titu1994/keras-octconv#2]
when setting alpha !=0.5 like 0.125
![image](https://user-images.githubusercontent.com/9452949/56485071-2aded800-6505-11e9-89aa-4c80000e505f.png)

**Comment by titu1994** [comment]
Interesting. I'll look into it tonight.

**Comment by titu1994** [comment]
Closed via d97be155b1d228c767288266492fde26560bbfbf
